# Generated by Django 5.0.3 on 2024-03-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
